### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by UmaSakthi13** [RyanZim/universalify#18]
'cannot read property 'name' of undefined' error occurring at the index file of universalify package

**Comment by RyanZim** [comment]
Please post a minimal reproducible example, along with a full stack trace.

**Comment by UmaSakthi13** [comment]
}, 'name', { value: fn.name })
                         ^
TypeError: Cannot read property 'name' of undefined

We had package versions upgraded for several packages after which we are facing this error during deployment using Jenkins.

universalify- ^2.0.0 is the version given in package.josn file

**Comment by RyanZim** [comment]
It would appear that something is calling universalify with `undefined`; without a stack trace, it's impossible to determine what.

**Comment by peteriman** [comment]
@UmaSakthi13, you should provide the full stack trace which looks like the following:

```
Uncaught TypeError: Cannot read property 'name' of undefined
    at exports.fromCallback (/home/user/test/node_modules/universalify/index.js:15:26)
    at Object.<anonymous> (<some file path here>:<line number>:<column number>)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
```

You might also want to determine if it's caused by upgrades, notably fs-extra@^10.0.0`.

**Comment by RyanZim** [comment]
Closing for lack of response.
